Repository hlxsites/vg-macktrucks-com, pull requests merged in 2024-10, with the labels that each got.

#882 Newfeed generator
  .github/ci/generate-news-feed.js
Labels: Ignore for release

#881 Delete spacing when one character is in italics #773
  scripts/common.js
  scripts/scripts.js
Labels: Enhancement, FR, Injection

#886 Release 27
  blocks/search/search.js
  package-lock.json
  package.json
  scripts/common.js
  scripts/scripts.js
Labels: Ignore for release

#876 867 fix search tags
  blocks/explore-articles/explore-articles.js
  blocks/recent-articles/recent-articles.js
  scripts/common.js
Labels: NFR

#888 Atom Feed generation for all markets #880
  .github/ci/generate-news-feed-config.js
  .github/ci/generate-news-feed.js
  config-patches/vg-macktrucks-co-nz.patch
  config-patches/vg-macktrucks-com-au.patch
  config-patches/vg-macktrucks-com-museum.patch
  config-patches/vg-macktrucks-com-mx.patch
  config-patches/vg-macktrucks-com-ve.patch
  mack-news.json
  mack-news/bs/feed.xml
  mack-news/ca/feed.xml
  mack-news/cl/feed.xml
  mack-news/co-nz/feed.xml
  mack-news/com-ar/feed.xml
  mack-news/com-au/feed.xml
  mack-news/com-bo/feed.xml
  mack-news/com-co/feed.xml
  mack-news/com-do/feed.xml
  mack-news/com-ec/feed.xml
  mack-news/com-gy/feed.xml
  mack-news/com-mx/feed.xml
  mack-news/com-ng/feed.xml
  mack-news/com-ni/feed.xml
  mack-news/com-pa/feed.xml
  mack-news/com-pe/feed.xml
  mack-news/com-ve/feed.xml
  mack-news/com/feed.xml
  mack-news/cr/feed.xml
  mack-news/emea/feed.xml
  mack-news/gt/feed.xml
  mack-news/hn/feed.xml
  mack-news/ht/feed.xml
  mack-news/museum/feed.xml
  mack-news/sv/feed.xml
  mack-news/tt/feed.xml
  parts-and-services/support/body-builders/news-and-events/bs/feed.xml
  parts-and-services/support/body-builders/news-and-events/ca/feed.xml
  parts-and-services/support/body-builders/news-and-events/cl/feed.xml
  parts-and-services/support/body-builders/news-and-events/co-nz/feed.xml
  parts-and-services/support/body-builders/news-and-events/com-ar/feed.xml
  parts-and-services/support/body-builders/news-and-events/com-au/feed.xml
  parts-and-services/support/body-builders/news-and-events/com-bo/feed.xml
  parts-and-services/support/body-builders/news-and-events/com-co/feed.xml
  parts-and-services/support/body-builders/news-and-events/com-do/feed.xml
  parts-and-services/support/body-builders/news-and-events/com-ec/feed.xml
  parts-and-services/support/body-builders/news-and-events/com-gy/feed.xml
  parts-and-services/support/body-builders/news-and-events/com-mx/feed.xml
  parts-and-services/support/body-builders/news-and-events/com-ng/feed.xml
  parts-and-services/support/body-builders/news-and-events/com-ni/feed.xml
  parts-and-services/support/body-builders/news-and-events/com-pa/feed.xml
  parts-and-services/support/body-builders/news-and-events/com-pe/feed.xml
  parts-and-services/support/body-builders/news-and-events/com-ve/feed.xml
  parts-and-services/support/body-builders/news-and-events/com/feed.xml
  parts-and-services/support/body-builders/news-and-events/cr/feed.xml
  parts-and-services/support/body-builders/news-and-events/emea/feed.xml
  parts-and-services/support/body-builders/news-and-events/gt/feed.xml
  parts-and-services/support/body-builders/news-and-events/hn/feed.xml
  parts-and-services/support/body-builders/news-and-events/ht/feed.xml
  parts-and-services/support/body-builders/news-and-events/museum/feed.xml
  parts-and-services/support/body-builders/news-and-events/sv/feed.xml
  parts-and-services/support/body-builders/news-and-events/tt/feed.xml
Labels: FR

#877 Breadcrumb block made authorable #770
  blocks/v2-breadcrumb/v2-breadcrumb.css
  blocks/v2-breadcrumb/v2-breadcrumb.js
  scripts/common.js
Labels: Enhancement, NFR, Injection

#892 Fix v2-accordion #891
  blocks/v2-accordion/v2-accordion.js
Labels: Bugfix

#896 Add video property in helix-query.yaml for magazine articles #753
  helix-query.yaml
Labels: FR

#894 [V2 Recommendations] New Block - Recommended Articles #750
  blocks/recent-articles/recent-articles.js
  blocks/recommendations/recommendations.js
  blocks/v2-recommendations/v2-recommendations.css
  blocks/v2-recommendations/v2-recommendations.js
  scripts/services/magazine.service.js
Labels: FR

#897 V2 Social Block #748
  blocks/v2-social-block/v2-social-block.css
  blocks/v2-social-block/v2-social-block.js
  icons/fb.svg
  icons/link.svg
  icons/twitter.svg
  icons/yt.svg
  placeholder.json
  styles/styles.css
Labels: FR, Bulldog magazine

#901 Release 28
  blocks/explore-articles/explore-articles.js
  blocks/recent-articles/recent-articles.js
  blocks/recommendations/recommendations.css
  blocks/recommendations/recommendations.js
  blocks/v2-breadcrumb/v2-breadcrumb.css
  blocks/v2-breadcrumb/v2-breadcrumb.js
  blocks/v2-explore-articles/v2-explore-articles.js
  blocks/v2-magazine-tabbed-carousel/v2-magazine-tabbed-carousel.js
  blocks/v2-recommendations/v2-recommendations.css
  blocks/v2-recommendations/v2-recommendations.js
  blocks/v2-social-block/v2-social-block.css
  blocks/v2-social-block/v2-social-block.js
  icons/fb.svg
  icons/link.svg
  icons/twitter.svg
  icons/yt.svg
  package-lock.json
  package.json
  placeholder.json
  scripts/common.js
  scripts/services/magazine.service.js
  styles/styles.css
  templates/magazine/magazine.js
Labels: Ignore for release
