Repository hlxsites/vg-macktrucks-com, pull requests merged in 2024-07, with the labels that each got.

#782 v5 aem.js loadCSS returns a promise
  common/modal/modal-component.js
Labels: Bugfix

#765 4 row v2-cards variant #593
  blocks/v2-cards/v2-cards.css
  blocks/v2-cards/v2-cards.js
  scripts/scripts.js
  styles/styles.css
Labels: FR

#786 Release 20
  blocks/v2-cards/v2-cards.css
  blocks/v2-cards/v2-cards.js
  blocks/v2-category-collage/v2-category-collage.css
  blocks/v2-category-collage/v2-category-collage.js
  blocks/v2-magazine-tabbed-carousel/v2-magazine-tabbed-carousel.css
  blocks/v2-magazine-tabbed-carousel/v2-magazine-tabbed-carousel.js
  constants.json
  placeholder.json
  scripts/scripts.js
  scripts/video-helper.js
  styles/styles.css
  templates/magazine/magazine.js
Labels: Ignore for release

#796 V2 embed video broken #795
  blocks/v2-embed/v2-embed.js
Labels: Bugfix

#801 Release 21
  .github/workflows/run-tests.yaml
  blocks/v2-embed/v2-embed.js
  blocks/v2-product-listing/v2-product-listing.css
  blocks/v2-product-listing/v2-product-listing.js
  blocks/v2-truck-features/v2-truck-features.css
  package.json
Labels: Ignore for release

#762 Alert for content editors on incorrect block usage #624
  common/snackbar/snackbar.css
  common/snackbar/snackbar.js
  constants.json
  icons/checkmark-circle.svg
  icons/remove.svg
  package-lock.json
  scripts/common.js
  scripts/delayed.js
  scripts/validate-elements.js
  styles/styles.css
Labels: NFR

#800 CSS Adjustment for Superscript #778
  blocks/header/header.css
  blocks/v2-hero/v2-hero.css
  blocks/v2-product-listing/v2-product-listing.css
  styles/styles.css
Labels: FR

#811 Release 22
  blocks/header/header.css
  blocks/v2-cards/v2-cards.css
  blocks/v2-cards/v2-cards.js
  blocks/v2-category-collage/v2-category-collage.css
  blocks/v2-category-collage/v2-category-collage.js
  blocks/v2-hero/v2-hero.css
  blocks/v2-product-listing/v2-product-listing.css
  common/snackbar/snackbar.css
  common/snackbar/snackbar.js
  constants.json
  icons/bullet.svg
  icons/checkmark-circle.svg
  icons/remove.svg
  package-lock.json
  package.json
  scripts/common.js
  scripts/delayed.js
  scripts/validate-elements.js
  styles/styles.css
Labels: Ignore for release
