Repository hlxsites/vg-macktrucks-com, pull requests merged in 2024-08, with the labels that each got.

#812 [Magazine Hero] - Hero Variant #746
  blocks/v2-hero/v2-hero.css
  blocks/v2-hero/v2-hero.js
Labels: FR

#814 FIX [Block library] add to whitelist #813
  blocks/v2-cards/v2-cards.js
  constants.json
Labels: Defect, Technical debt

#820 Images grid "with-captions" variant #745
  blocks/v2-images-grid/v2-images-grid.css
  blocks/v2-images-grid/v2-images-grid.js
Labels: FR

#819 filters as placeholders & dynamic collage content #602
  blocks/v2-explore-articles/v2-explore-articles.css
  blocks/v2-explore-articles/v2-explore-articles.js
  icons/chevron-down.svg
  placeholder.json
Labels: FR

#823 Search: Updating the Metadata for Magazine Search (1 of 5) #683
  helix-query.yaml
Labels: FR

#821 Country limiter for truck configurator in non-included countries #789
  blocks/dealer-locator/dealer-locator.js
  blocks/dealer-locator/sidebar-maps.js
  constants.json
  scripts/scripts.js
  scripts/validate-countries.js
Labels: FR

#831 fix: Fix assets plugin in sidekick config
  tools/sidekick/config.json
Labels: Ignore for release

#825 refactor Magazine template
  blocks/recent-articles/recent-articles.js
  blocks/recommendations/recommendations.js
  scripts/common.js
  templates/magazine/magazine.js
Labels: FR

#840 Dealer Locator fixes applied to V2 new format
  blocks/v2-dealer-locator/shared/template.js
  blocks/v2-dealer-locator/v2-dealer-locator.css
  blocks/v2-dealer-locator/versions/default/sidebar-maps.js
  blocks/v2-dealer-locator/versions/export/dealer-locator.css
  blocks/v2-dealer-locator/versions/export/sidebar-maps.js
Labels: Bugfix

#841 subscribe button & form not render if is disabled #818
  blocks/iframe/iframe.js
  blocks/magazine-subscribe/magazine-subscribe.js
  blocks/sub-nav/sub-nav.js
Labels: Bugfix

#843 Image Banner #749
  blocks/v2-image-banner/v2-image-banner.css
  blocks/v2-image-banner/v2-image-banner.js
Labels: FR
