Repository hlxsites/vg-macktrucks-com, pull requests merged in 2024-09, with the labels that each got.

#853 766 add magazines metadata to search
  helix-query.yaml
Labels: Bulldog magazine

#854 Move Mack News configs to sharepoint #851
  .github/ci/generate-news-feed-config.js
  .github/ci/generate-news-feed.js
  .github/workflows/generate-atom-news-feeds.yaml
  .github/workflows/run-tests.yaml
  blocks/breadcrumb/breadcrumb.js
  blocks/v2-dealer-locator/v2-dealer-locator.js
  constants.json
  scripts/common.js
  scripts/scripts.js
Labels: NFR

#871 Release 26
  blocks/v2-pull-quote/v2-pull-quote.css
  blocks/v2-pull-quote/v2-pull-quote.js
  head.html
  package-lock.json
  package.json
  scripts/common.js
Labels: Ignore for release
